name: flutter_easy_new
description: A Flutter Learning App.

publish_to: 'none'

version: 5.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  backdrop:
  animated_floatactionbuttons:
  liquid_swipe:
  quick_actions:
  flutter_swiper:
  charts_flutter:
  curved_navigation_bar:
  english_words:
  flutter_bloc:
  flutter_gallery_assets:
  flutter_markdown:
  flutter_webview_plugin:
  flutter_auth_buttons:
  flutter_colorpicker:
  speedometer:
  vertical_card_pager:
  flutter_custom_clippers:
  share:
  fluttertoast:
  google_sign_in:
  http:
  image_picker:
  lottie:
  badges:
  shimmer:
  package_info:
  path_provider:
  path:
  provider:
  scoped_model:
  sembast:
  splashscreen:
  url_launcher:
  shared_preferences:
  sqflite:
  substring_highlight:
  widget_with_codeview:
  transparent_image:
  intro_views_flutter:
  timeline_list:
  shrink_sidemenu:
  flutter_multi_carousel:
  scratcher:
  async:
  cached_network_image:
  video_player:
  story_view:
  local_auth:
  toggle_bar:
  giffy_dialog:
  liquid_ui:
  spincircle_bottom_bar:
  lamp_bottom_navigation:
  bubble_bottom_bar:
  line_icons:
  font_awesome_flutter:
  palette_generator:
  clipboard:
  connectivity:
  settings_ui:
  slimy_card:
  timer_builder:
  flutter_ticket_widget:
  flutter_spinning_wheel:
  confetti:
  snappable:
  sticky_grouped_list:
  bubble:
  polls:
  flutter_neumorphic:
  wave:
  liquid_pull_to_refresh:
  flip_card:
  bubble_timeline:
  flutter_rating_bar:
  fancy_drawer:
  carousel_pro:
  flutter_staggered_grid_view:
  flutter_chess_board:
  flutter_custom_credit_card_ui:
  passcode_screen:
  motion_tab_bar:
  pandabar:
  slider_button:
  floating_bottom_navigation_bar:
  sms_otp_auto_verify:
  wave_slider:
  progressive_image:
  imageview360:
  before_after:
  side_menu_animation:
  elastic_drawer:
  animated_drawer:
  foldable_sidebar:
  status_alert:
  radial_menu:
  flutter_anywhere_menus:
  floatingpanel:
  decorative_app_bar:
  fluent_appbar:
  navigation_rail: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - lib/models/
    - lib/routes/
    - res/images/
    - res/lottie/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Medium.ttf
